### ISSUE TITLE
Please add more information about your client ^^

### ISSUE THREAD

**Issue by hugmouse** [jfoucher/Jimmy#1]
Hi! Stumbled across your client by chance, would like you to add a README.md with some information about your client and what it looks like. 

I'll also leave two screenshots below, so that if someone also found this client did not have to compile it to see what it looks like, hehe

## Screenshots

Version: https://github.com/jfoucher/Jimmy/commit/5f541efaf3b53dbd9a30cc7ba2c2a6776fbf51fe

![small window](https://user-images.githubusercontent.com/44648612/154664425-ef9f87ef-0cc2-49c7-beea-8ed97f297c38.png)
![fullscreen](https://user-images.githubusercontent.com/44648612/154664123-bd6b9e6f-92d7-4c61-9639-40fd93031055.png)

**Comment by hugmouse** [comment]
Also here is universal app, both x86 and ARM for MacOS!

[jimmy.zip](https://github.com/jfoucher/Jimmy/files/8096413/jimmy.zip)

**Comment by jfoucher** [comment]
Wow ok I literally just put this up yesterday and you found it already :D

This is still a very early version that’s not ready for public use at all, I only spent two days on it so far.   But yes I definitely plan on adding a readme with screenshots and binary releases when I feel that the app is at that stage.
