### ISSUE TITLE
Don't require "gemini://" before domain

### ISSUE THREAD

**Issue by ghost** [jfoucher/Jimmy#12]
Ón version 1.2, I could just type cugi.ie to get to that capsule. With v2.0 I have to type the redundant "gemini://" beforehand. Application can assume that unspecified protocol is gemini.

**Comment by jfoucher** [comment]
Should be fixed in [v0.2.1 ](https://github.com/jfoucher/Jimmy/releases/tag/v0.2.1)
Could you check and let me know?
Thanks
