### ISSUE TITLE
Feature request: Use pointer icon for mouse when hovering over link line

### ISSUE THREAD

**Issue by acidus99** [jfoucher/Jimmy#22]
Please consider updating Jimmy to use the `pointer` icon for the mouse cursor when hovering over a link. Currently it always shows an arrow, which is different than what other GUI Gemini browsers or Web browsers do, which feels a little odd to use

**Comment by acidus99** [comment]
I think there might be a bug with cursors in general. Sometimes I have an i-beam / `text` icon, other times an arrow, other times a pointer. I'll see if I can find out how to reproduce this but honestly just browsing around a few capsules I found this behavior

**Comment by jfoucher** [comment]
@acidus99 Can you please send me a link where you can reproduce this behaviour? I haven't been able to reproduce it. Thanks

**Comment by acidus99** [comment]
sure, let me try. it was a little odd to reproduce
