### ISSUE TITLE
Reloading a page adds a duplicate entry to the history

### ISSUE THREAD

**Issue by acidus99** [jfoucher/Jimmy#23]
If you visit a page, and then click the reload button, when you push the back button, it appears to the user that nothing happens. You must press the back button again to return the original page.

Steps to reproduce:
* Start on Page A
* Click a navigate to Page B
* Reload Page B
* Click the back button

Expected: you are on Page A
Actual: you are on Page B

It gets worse because if you click reload on Page B multiple times, the user must click the back button that many times before they return back to Page A. This is very jarring.

I suppose this could be considered expected behavior, since you are going "back" to what Page B looked like at a previous time. However no other Web browser or gemini browser works this way. 

I suspect that a list is is being used to track history, and clicking reload adds another entry to the list. I suggest that reloading a page should not add a new entry to the history list

**Comment by jfoucher** [comment]
@acidus99 Should be fixed in https://github.com/jfoucher/Jimmy/commit/d1a5c50ec81285a999fbe035bc0e73ed7297b1d5

**Comment by acidus99** [comment]
Thank you!
