### ISSUE TITLE
Won't open on MacBook Air M1 running macOS Sonoma 14.1

### ISSUE THREAD

**Issue by poksiala** [jfoucher/Jimmy#25]
HI,

I tried to install it according to instruction in readme. Apple seems to prevent the app from running: “jimmy” can’t be opened because Apple cannot check it for malicious software.
<img width="294" alt="jimmy can’t be opened because Apple cannot check it for malicious software." src="https://github.com/jfoucher/Jimmy/assets/18363643/a325b912-7f41-40db-ab5e-15c917a14e46">

**Comment by jfoucher** [comment]
This is because the app is not signed since Apple charges 100€ a year to do that. You can either right click the icon and select open, or build the app from source using XCode. Hope that helps.

**Comment by poksiala** [comment]
Thank you for the reply. You are correct. Maybe the ux has changed a bit as I have added these security exceptions many times on previous macos versions, but this time I didn't even think of it.
