### ISSUE TITLE
pressing space in URL bar causes crash [Apple Silicon]

### ISSUE THREAD

**Issue by ghost** [jfoucher/Jimmy#8]
I was testing to see if search was possible and when I put focus in the URL bar, the first thing I did was press the spacebar. I can consistently reproduce crashing the application this way.

macOS 12.2.1

**Comment by jfoucher** [comment]
Is this with the latest release? (0.2.0)

**Comment by ghost** [comment]
No. Version 0.1.2 (1). Seems fine in version 2.0!

**Comment by jfoucher** [comment]
Ok great
