### ISSUE TITLE
Search within page

### ISSUE THREAD

**Issue by ghost** [jfoucher/Jimmy#9]
It would be great to be able to press cmd + f and be presented with a field to enter search terms, like in Safari.

**Comment by jfoucher** [comment]
Yes, this will probably be fixed at the same time as #10

**Comment by jfoucher** [comment]
Search now works in [v0.2.2](https://github.com/jfoucher/Jimmy/releases/tag/v0.2.2). However having a keyboard shortcut for this is not so easy, and will come at a later date.
